#!/bin/sh
qemu-system-arm \
	-M versatilepb \
	--kernel buildroot/output/images/zImage \
	-dtb buildroot/output/images/versatile-pb.dtb \
	-drive file=buildroot/output/images/rootfs.ext2,if=scsi,format=raw \
	--append "root=/dev/sda console=ttyAMA0,115200" \
	--serial stdio \
	--net nic,model=rtl8139 \
	--net user
 
